import {createFileRoute,Link} from "@tanstack/react-router";
import {ArrowLeft,Clock3,MapPin,UsersRound,Navigation,BadgeCheck,CarFront} from "lucide-react";
import {communityEvents} from "@/lib/community-events";
import {useRideState,type Ride} from "@/lib/rides-data";
import {CommunityBottomNav} from "@/components/community/CommunityBottomNav";
export const Route=createFileRoute("/event/$eventId/pickups")({component:PickupOffers});
function PickupOffers(){
 const {eventId}=Route.useParams();const s=useRideState();const event=communityEvents.find(e=>e.id===eventId);
 const rides=s.rides.filter(r=>r.eventId===eventId&&r.direction==="outbound"&&["open","full"].includes(r.status));
 const groups=Object.entries(rides.reduce<Record<string,Ride[]>>((a,r)=>{const key=r.meetingPoint||r.from;(a[key]??=[]).push(r);return a},{}));
 if(!event)return <main className="p-6">Event not found.</main>;
 return <div className="min-h-screen bg-muted/30 pb-24"><header className="border-b bg-background px-5 py-5"><div className="mx-auto max-w-md"><Link to="/event/$eventId" params={{eventId}} className="mb-4 flex items-center gap-2 text-xs font-bold text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Event details</Link><p className="text-[10px] font-bold uppercase tracking-[.14em] text-primary">{event.name}</p><h1 className="mt-1 text-2xl font-black">Pickup locations</h1><p className="mt-2 text-xs leading-5 text-muted-foreground">Driver offers grouped by pickup point. Open an offer to view the ride and request a seat.</p></div></header><main className="mx-auto max-w-md space-y-5 px-5 pt-5">{groups.map(([location,offers])=><section key={location} className="overflow-hidden rounded-2xl border bg-card"><div className="border-b bg-muted/50 p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-soft text-primary"><MapPin className="h-5 w-5"/></span><div><h2 className="text-sm font-black">{location}</h2><p className="mt-1 text-[11px] text-muted-foreground">{offers[0]?.from} pickup area</p><p className="mt-1 text-[11px] font-semibold text-primary">{offers.length} driver offer{offers.length===1?"":"s"} · {offers.reduce((n,r)=>n+r.seats,0)} seats available</p></div><a href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(location+", Abuja")} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()} className="ml-auto flex h-9 w-9 items-center justify-center rounded-full border text-primary"><Navigation className="h-4 w-4"/></a></div></div><div className="divide-y">{offers.map(r=><Link key={r.id} to="/rides/$rideId" params={{rideId:r.id}} className="block p-4 hover:bg-muted/40"><div className="flex justify-between gap-3"><div><p className="flex items-center gap-1 text-sm font-bold">{r.driver}{r.verified&&<BadgeCheck className="h-4 w-4 text-success"/>}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-muted-foreground"><CarFront className="h-3 w-3"/>{r.vehicle}</p></div><span className="h-fit rounded-full bg-success/10 px-2 py-1 text-[10px] font-bold text-success">{r.seats} seat{r.seats===1?"":"s"}</span></div><p className="mt-3 flex items-center gap-1 text-[11px] text-muted-foreground"><MapPin className="h-3.5 w-3.5"/>Meeting point: {r.meetingPoint||r.from}</p><div className="mt-2 flex justify-between text-xs"><span className="flex items-center gap-1 text-muted-foreground"><Clock3 className="h-3.5 w-3.5"/>{r.time}</span><span className="font-bold">{r.contribution?"₦"+r.contribution.toLocaleString():"Free"}</span></div></Link>)}</div></section>)}{groups.length===0&&<div className="rounded-2xl border border-dashed bg-card p-6 text-center"><UsersRound className="mx-auto h-6 w-6 text-muted-foreground"/><p className="mt-3 text-sm font-bold">No pickup offers yet</p></div>}</main><CommunityBottomNav/></div>
}