/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RoleRouteImport } from './routes/role'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as HostRouteImport } from './routes/host'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrustReviewsRouteImport } from './routes/trust.reviews'
import { Route as TrustKycRouteImport } from './routes/trust.kyc'
import { Route as TrustDisputesRouteImport } from './routes/trust.disputes'
import { Route as SignupHostRouteImport } from './routes/signup.host'
import { Route as SignupCorporateRouteImport } from './routes/signup.corporate'
import { Route as PaymentsPayoutsRouteImport } from './routes/payments.payouts'
import { Route as PaymentsMethodsRouteImport } from './routes/payments.methods'
import { Route as OffersNegotiationIdRouteImport } from './routes/offers.$negotiationId'
import { Route as HostVehiclesRouteImport } from './routes/host.vehicles'
import { Route as HostOffersRouteImport } from './routes/host.offers'
import { Route as HostEngagedRouteImport } from './routes/host.engaged'
import { Route as HostEarningsRouteImport } from './routes/host.earnings'
import { Route as CorporateRequestsRouteImport } from './routes/corporate.requests'
import { Route as CorporateOffersRouteImport } from './routes/corporate.offers'
import { Route as CorporateDealsRouteImport } from './routes/corporate.deals'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminMoreRouteImport } from './routes/admin.more'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as PaymentsReceiptsIndexRouteImport } from './routes/payments.receipts.index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminFinanceIndexRouteImport } from './routes/admin.finance.index'
import { Route as TrustReviewDealIdRouteImport } from './routes/trust.review.$dealId'
import { Route as TrustDisputesNewRouteImport } from './routes/trust.disputes.new'
import { Route as TrustDisputesDisputeIdRouteImport } from './routes/trust.disputes.$disputeId'
import { Route as PaymentsReceiptsTxnIdRouteImport } from './routes/payments.receipts.$txnId'
import { Route as CorporateRequestsRequestIdRouteImport } from './routes/corporate.requests.$requestId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminFinanceTransactionsRouteImport } from './routes/admin.finance.transactions'
import { Route as AdminFinancePayoutsRouteImport } from './routes/admin.finance.payouts'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrustReviewsRoute = TrustReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => TrustRoute,
} as any)
const TrustKycRoute = TrustKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => TrustRoute,
} as any)
const TrustDisputesRoute = TrustDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => TrustRoute,
} as any)
const SignupHostRoute = SignupHostRouteImport.update({
  id: '/signup/host',
  path: '/signup/host',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCorporateRoute = SignupCorporateRouteImport.update({
  id: '/signup/corporate',
  path: '/signup/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsPayoutsRoute = PaymentsPayoutsRouteImport.update({
  id: '/payments/payouts',
  path: '/payments/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsMethodsRoute = PaymentsMethodsRouteImport.update({
  id: '/payments/methods',
  path: '/payments/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersNegotiationIdRoute = OffersNegotiationIdRouteImport.update({
  id: '/$negotiationId',
  path: '/$negotiationId',
  getParentRoute: () => OffersRoute,
} as any)
const HostVehiclesRoute = HostVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => HostRoute,
} as any)
const HostOffersRoute = HostOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => HostRoute,
} as any)
const HostEngagedRoute = HostEngagedRouteImport.update({
  id: '/engaged',
  path: '/engaged',
  getParentRoute: () => HostRoute,
} as any)
const HostEarningsRoute = HostEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => HostRoute,
} as any)
const CorporateRequestsRoute = CorporateRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CorporateRoute,
} as any)
const CorporateOffersRoute = CorporateOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => CorporateRoute,
} as any)
const CorporateDealsRoute = CorporateDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => CorporateRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoreRoute = AdminMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const PaymentsReceiptsIndexRoute = PaymentsReceiptsIndexRouteImport.update({
  id: '/payments/receipts/',
  path: '/payments/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceIndexRoute = AdminFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AdminRoute,
} as any)
const TrustReviewDealIdRoute = TrustReviewDealIdRouteImport.update({
  id: '/review/$dealId',
  path: '/review/$dealId',
  getParentRoute: () => TrustRoute,
} as any)
const TrustDisputesNewRoute = TrustDisputesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TrustDisputesRoute,
} as any)
const TrustDisputesDisputeIdRoute = TrustDisputesDisputeIdRouteImport.update({
  id: '/$disputeId',
  path: '/$disputeId',
  getParentRoute: () => TrustDisputesRoute,
} as any)
const PaymentsReceiptsTxnIdRoute = PaymentsReceiptsTxnIdRouteImport.update({
  id: '/payments/receipts/$txnId',
  path: '/payments/receipts/$txnId',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRequestsRequestIdRoute =
  CorporateRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => CorporateRequestsRoute,
  } as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceTransactionsRoute =
  AdminFinanceTransactionsRouteImport.update({
    id: '/finance/transactions',
    path: '/finance/transactions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminFinancePayoutsRoute = AdminFinancePayoutsRouteImport.update({
  id: '/finance/payouts',
  path: '/finance/payouts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/corporate': typeof CorporateRouteWithChildren
  '/feed': typeof FeedRoute
  '/host': typeof HostRouteWithChildren
  '/offers': typeof OffersRouteWithChildren
  '/role': typeof RoleRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/corporate/deals': typeof CorporateDealsRoute
  '/corporate/offers': typeof CorporateOffersRoute
  '/corporate/requests': typeof CorporateRequestsRouteWithChildren
  '/host/earnings': typeof HostEarningsRoute
  '/host/engaged': typeof HostEngagedRoute
  '/host/offers': typeof HostOffersRoute
  '/host/vehicles': typeof HostVehiclesRoute
  '/offers/$negotiationId': typeof OffersNegotiationIdRoute
  '/payments/methods': typeof PaymentsMethodsRoute
  '/payments/payouts': typeof PaymentsPayoutsRoute
  '/signup/corporate': typeof SignupCorporateRoute
  '/signup/host': typeof SignupHostRoute
  '/trust/disputes': typeof TrustDisputesRouteWithChildren
  '/trust/kyc': typeof TrustKycRoute
  '/trust/reviews': typeof TrustReviewsRoute
  '/admin/': typeof AdminIndexRoute
  '/host/': typeof HostIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/corporate/requests/$requestId': typeof CorporateRequestsRequestIdRoute
  '/payments/receipts/$txnId': typeof PaymentsReceiptsTxnIdRoute
  '/trust/disputes/$disputeId': typeof TrustDisputesDisputeIdRoute
  '/trust/disputes/new': typeof TrustDisputesNewRoute
  '/trust/review/$dealId': typeof TrustReviewDealIdRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/payments/receipts/': typeof PaymentsReceiptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corporate': typeof CorporateRouteWithChildren
  '/feed': typeof FeedRoute
  '/offers': typeof OffersRouteWithChildren
  '/role': typeof RoleRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/corporate/deals': typeof CorporateDealsRoute
  '/corporate/offers': typeof CorporateOffersRoute
  '/corporate/requests': typeof CorporateRequestsRouteWithChildren
  '/host/earnings': typeof HostEarningsRoute
  '/host/engaged': typeof HostEngagedRoute
  '/host/offers': typeof HostOffersRoute
  '/host/vehicles': typeof HostVehiclesRoute
  '/offers/$negotiationId': typeof OffersNegotiationIdRoute
  '/payments/methods': typeof PaymentsMethodsRoute
  '/payments/payouts': typeof PaymentsPayoutsRoute
  '/signup/corporate': typeof SignupCorporateRoute
  '/signup/host': typeof SignupHostRoute
  '/trust/disputes': typeof TrustDisputesRouteWithChildren
  '/trust/kyc': typeof TrustKycRoute
  '/trust/reviews': typeof TrustReviewsRoute
  '/admin': typeof AdminIndexRoute
  '/host': typeof HostIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/corporate/requests/$requestId': typeof CorporateRequestsRequestIdRoute
  '/payments/receipts/$txnId': typeof PaymentsReceiptsTxnIdRoute
  '/trust/disputes/$disputeId': typeof TrustDisputesDisputeIdRoute
  '/trust/disputes/new': typeof TrustDisputesNewRoute
  '/trust/review/$dealId': typeof TrustReviewDealIdRoute
  '/admin/finance': typeof AdminFinanceIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/payments/receipts': typeof PaymentsReceiptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/corporate': typeof CorporateRouteWithChildren
  '/feed': typeof FeedRoute
  '/host': typeof HostRouteWithChildren
  '/offers': typeof OffersRouteWithChildren
  '/role': typeof RoleRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/corporate/deals': typeof CorporateDealsRoute
  '/corporate/offers': typeof CorporateOffersRoute
  '/corporate/requests': typeof CorporateRequestsRouteWithChildren
  '/host/earnings': typeof HostEarningsRoute
  '/host/engaged': typeof HostEngagedRoute
  '/host/offers': typeof HostOffersRoute
  '/host/vehicles': typeof HostVehiclesRoute
  '/offers/$negotiationId': typeof OffersNegotiationIdRoute
  '/payments/methods': typeof PaymentsMethodsRoute
  '/payments/payouts': typeof PaymentsPayoutsRoute
  '/signup/corporate': typeof SignupCorporateRoute
  '/signup/host': typeof SignupHostRoute
  '/trust/disputes': typeof TrustDisputesRouteWithChildren
  '/trust/kyc': typeof TrustKycRoute
  '/trust/reviews': typeof TrustReviewsRoute
  '/admin/': typeof AdminIndexRoute
  '/host/': typeof HostIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/corporate/requests/$requestId': typeof CorporateRequestsRequestIdRoute
  '/payments/receipts/$txnId': typeof PaymentsReceiptsTxnIdRoute
  '/trust/disputes/$disputeId': typeof TrustDisputesDisputeIdRoute
  '/trust/disputes/new': typeof TrustDisputesNewRoute
  '/trust/review/$dealId': typeof TrustReviewDealIdRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/payments/receipts/': typeof PaymentsReceiptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/corporate'
    | '/feed'
    | '/host'
    | '/offers'
    | '/role'
    | '/terms'
    | '/trust'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/disputes'
    | '/admin/kyc'
    | '/admin/moderation'
    | '/admin/more'
    | '/admin/settings'
    | '/corporate/deals'
    | '/corporate/offers'
    | '/corporate/requests'
    | '/host/earnings'
    | '/host/engaged'
    | '/host/offers'
    | '/host/vehicles'
    | '/offers/$negotiationId'
    | '/payments/methods'
    | '/payments/payouts'
    | '/signup/corporate'
    | '/signup/host'
    | '/trust/disputes'
    | '/trust/kyc'
    | '/trust/reviews'
    | '/admin/'
    | '/host/'
    | '/payments/'
    | '/admin/finance/payouts'
    | '/admin/finance/transactions'
    | '/admin/users/$userId'
    | '/corporate/requests/$requestId'
    | '/payments/receipts/$txnId'
    | '/trust/disputes/$disputeId'
    | '/trust/disputes/new'
    | '/trust/review/$dealId'
    | '/admin/finance/'
    | '/admin/users/'
    | '/payments/receipts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corporate'
    | '/feed'
    | '/offers'
    | '/role'
    | '/terms'
    | '/trust'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/disputes'
    | '/admin/kyc'
    | '/admin/moderation'
    | '/admin/more'
    | '/admin/settings'
    | '/corporate/deals'
    | '/corporate/offers'
    | '/corporate/requests'
    | '/host/earnings'
    | '/host/engaged'
    | '/host/offers'
    | '/host/vehicles'
    | '/offers/$negotiationId'
    | '/payments/methods'
    | '/payments/payouts'
    | '/signup/corporate'
    | '/signup/host'
    | '/trust/disputes'
    | '/trust/kyc'
    | '/trust/reviews'
    | '/admin'
    | '/host'
    | '/payments'
    | '/admin/finance/payouts'
    | '/admin/finance/transactions'
    | '/admin/users/$userId'
    | '/corporate/requests/$requestId'
    | '/payments/receipts/$txnId'
    | '/trust/disputes/$disputeId'
    | '/trust/disputes/new'
    | '/trust/review/$dealId'
    | '/admin/finance'
    | '/admin/users'
    | '/payments/receipts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/corporate'
    | '/feed'
    | '/host'
    | '/offers'
    | '/role'
    | '/terms'
    | '/trust'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/disputes'
    | '/admin/kyc'
    | '/admin/moderation'
    | '/admin/more'
    | '/admin/settings'
    | '/corporate/deals'
    | '/corporate/offers'
    | '/corporate/requests'
    | '/host/earnings'
    | '/host/engaged'
    | '/host/offers'
    | '/host/vehicles'
    | '/offers/$negotiationId'
    | '/payments/methods'
    | '/payments/payouts'
    | '/signup/corporate'
    | '/signup/host'
    | '/trust/disputes'
    | '/trust/kyc'
    | '/trust/reviews'
    | '/admin/'
    | '/host/'
    | '/payments/'
    | '/admin/finance/payouts'
    | '/admin/finance/transactions'
    | '/admin/users/$userId'
    | '/corporate/requests/$requestId'
    | '/payments/receipts/$txnId'
    | '/trust/disputes/$disputeId'
    | '/trust/disputes/new'
    | '/trust/review/$dealId'
    | '/admin/finance/'
    | '/admin/users/'
    | '/payments/receipts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CorporateRoute: typeof CorporateRouteWithChildren
  FeedRoute: typeof FeedRoute
  HostRoute: typeof HostRouteWithChildren
  OffersRoute: typeof OffersRouteWithChildren
  RoleRoute: typeof RoleRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRouteWithChildren
  PaymentsMethodsRoute: typeof PaymentsMethodsRoute
  PaymentsPayoutsRoute: typeof PaymentsPayoutsRoute
  SignupCorporateRoute: typeof SignupCorporateRoute
  SignupHostRoute: typeof SignupHostRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  PaymentsReceiptsTxnIdRoute: typeof PaymentsReceiptsTxnIdRoute
  PaymentsReceiptsIndexRoute: typeof PaymentsReceiptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trust/reviews': {
      id: '/trust/reviews'
      path: '/reviews'
      fullPath: '/trust/reviews'
      preLoaderRoute: typeof TrustReviewsRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/kyc': {
      id: '/trust/kyc'
      path: '/kyc'
      fullPath: '/trust/kyc'
      preLoaderRoute: typeof TrustKycRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/disputes': {
      id: '/trust/disputes'
      path: '/disputes'
      fullPath: '/trust/disputes'
      preLoaderRoute: typeof TrustDisputesRouteImport
      parentRoute: typeof TrustRoute
    }
    '/signup/host': {
      id: '/signup/host'
      path: '/signup/host'
      fullPath: '/signup/host'
      preLoaderRoute: typeof SignupHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/corporate': {
      id: '/signup/corporate'
      path: '/signup/corporate'
      fullPath: '/signup/corporate'
      preLoaderRoute: typeof SignupCorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/payouts': {
      id: '/payments/payouts'
      path: '/payments/payouts'
      fullPath: '/payments/payouts'
      preLoaderRoute: typeof PaymentsPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/methods': {
      id: '/payments/methods'
      path: '/payments/methods'
      fullPath: '/payments/methods'
      preLoaderRoute: typeof PaymentsMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$negotiationId': {
      id: '/offers/$negotiationId'
      path: '/$negotiationId'
      fullPath: '/offers/$negotiationId'
      preLoaderRoute: typeof OffersNegotiationIdRouteImport
      parentRoute: typeof OffersRoute
    }
    '/host/vehicles': {
      id: '/host/vehicles'
      path: '/vehicles'
      fullPath: '/host/vehicles'
      preLoaderRoute: typeof HostVehiclesRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/offers': {
      id: '/host/offers'
      path: '/offers'
      fullPath: '/host/offers'
      preLoaderRoute: typeof HostOffersRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/engaged': {
      id: '/host/engaged'
      path: '/engaged'
      fullPath: '/host/engaged'
      preLoaderRoute: typeof HostEngagedRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/earnings': {
      id: '/host/earnings'
      path: '/earnings'
      fullPath: '/host/earnings'
      preLoaderRoute: typeof HostEarningsRouteImport
      parentRoute: typeof HostRoute
    }
    '/corporate/requests': {
      id: '/corporate/requests'
      path: '/requests'
      fullPath: '/corporate/requests'
      preLoaderRoute: typeof CorporateRequestsRouteImport
      parentRoute: typeof CorporateRoute
    }
    '/corporate/offers': {
      id: '/corporate/offers'
      path: '/offers'
      fullPath: '/corporate/offers'
      preLoaderRoute: typeof CorporateOffersRouteImport
      parentRoute: typeof CorporateRoute
    }
    '/corporate/deals': {
      id: '/corporate/deals'
      path: '/deals'
      fullPath: '/corporate/deals'
      preLoaderRoute: typeof CorporateDealsRouteImport
      parentRoute: typeof CorporateRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/more': {
      id: '/admin/more'
      path: '/more'
      fullPath: '/admin/more'
      preLoaderRoute: typeof AdminMoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/payments/receipts/': {
      id: '/payments/receipts/'
      path: '/payments/receipts'
      fullPath: '/payments/receipts/'
      preLoaderRoute: typeof PaymentsReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/': {
      id: '/admin/finance/'
      path: '/finance'
      fullPath: '/admin/finance/'
      preLoaderRoute: typeof AdminFinanceIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trust/review/$dealId': {
      id: '/trust/review/$dealId'
      path: '/review/$dealId'
      fullPath: '/trust/review/$dealId'
      preLoaderRoute: typeof TrustReviewDealIdRouteImport
      parentRoute: typeof TrustRoute
    }
    '/trust/disputes/new': {
      id: '/trust/disputes/new'
      path: '/new'
      fullPath: '/trust/disputes/new'
      preLoaderRoute: typeof TrustDisputesNewRouteImport
      parentRoute: typeof TrustDisputesRoute
    }
    '/trust/disputes/$disputeId': {
      id: '/trust/disputes/$disputeId'
      path: '/$disputeId'
      fullPath: '/trust/disputes/$disputeId'
      preLoaderRoute: typeof TrustDisputesDisputeIdRouteImport
      parentRoute: typeof TrustDisputesRoute
    }
    '/payments/receipts/$txnId': {
      id: '/payments/receipts/$txnId'
      path: '/payments/receipts/$txnId'
      fullPath: '/payments/receipts/$txnId'
      preLoaderRoute: typeof PaymentsReceiptsTxnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/requests/$requestId': {
      id: '/corporate/requests/$requestId'
      path: '/$requestId'
      fullPath: '/corporate/requests/$requestId'
      preLoaderRoute: typeof CorporateRequestsRequestIdRouteImport
      parentRoute: typeof CorporateRequestsRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/transactions': {
      id: '/admin/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/admin/finance/transactions'
      preLoaderRoute: typeof AdminFinanceTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/payouts': {
      id: '/admin/finance/payouts'
      path: '/finance/payouts'
      fullPath: '/admin/finance/payouts'
      preLoaderRoute: typeof AdminFinancePayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminMoreRoute: typeof AdminMoreRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFinancePayoutsRoute: typeof AdminFinancePayoutsRoute
  AdminFinanceTransactionsRoute: typeof AdminFinanceTransactionsRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminFinanceIndexRoute: typeof AdminFinanceIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminKycRoute: AdminKycRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminMoreRoute: AdminMoreRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFinancePayoutsRoute: AdminFinancePayoutsRoute,
  AdminFinanceTransactionsRoute: AdminFinanceTransactionsRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminFinanceIndexRoute: AdminFinanceIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CorporateRequestsRouteChildren {
  CorporateRequestsRequestIdRoute: typeof CorporateRequestsRequestIdRoute
}

const CorporateRequestsRouteChildren: CorporateRequestsRouteChildren = {
  CorporateRequestsRequestIdRoute: CorporateRequestsRequestIdRoute,
}

const CorporateRequestsRouteWithChildren =
  CorporateRequestsRoute._addFileChildren(CorporateRequestsRouteChildren)

interface CorporateRouteChildren {
  CorporateDealsRoute: typeof CorporateDealsRoute
  CorporateOffersRoute: typeof CorporateOffersRoute
  CorporateRequestsRoute: typeof CorporateRequestsRouteWithChildren
}

const CorporateRouteChildren: CorporateRouteChildren = {
  CorporateDealsRoute: CorporateDealsRoute,
  CorporateOffersRoute: CorporateOffersRoute,
  CorporateRequestsRoute: CorporateRequestsRouteWithChildren,
}

const CorporateRouteWithChildren = CorporateRoute._addFileChildren(
  CorporateRouteChildren,
)

interface HostRouteChildren {
  HostEarningsRoute: typeof HostEarningsRoute
  HostEngagedRoute: typeof HostEngagedRoute
  HostOffersRoute: typeof HostOffersRoute
  HostVehiclesRoute: typeof HostVehiclesRoute
  HostIndexRoute: typeof HostIndexRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostEarningsRoute: HostEarningsRoute,
  HostEngagedRoute: HostEngagedRoute,
  HostOffersRoute: HostOffersRoute,
  HostVehiclesRoute: HostVehiclesRoute,
  HostIndexRoute: HostIndexRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

interface OffersRouteChildren {
  OffersNegotiationIdRoute: typeof OffersNegotiationIdRoute
}

const OffersRouteChildren: OffersRouteChildren = {
  OffersNegotiationIdRoute: OffersNegotiationIdRoute,
}

const OffersRouteWithChildren =
  OffersRoute._addFileChildren(OffersRouteChildren)

interface TrustDisputesRouteChildren {
  TrustDisputesDisputeIdRoute: typeof TrustDisputesDisputeIdRoute
  TrustDisputesNewRoute: typeof TrustDisputesNewRoute
}

const TrustDisputesRouteChildren: TrustDisputesRouteChildren = {
  TrustDisputesDisputeIdRoute: TrustDisputesDisputeIdRoute,
  TrustDisputesNewRoute: TrustDisputesNewRoute,
}

const TrustDisputesRouteWithChildren = TrustDisputesRoute._addFileChildren(
  TrustDisputesRouteChildren,
)

interface TrustRouteChildren {
  TrustDisputesRoute: typeof TrustDisputesRouteWithChildren
  TrustKycRoute: typeof TrustKycRoute
  TrustReviewsRoute: typeof TrustReviewsRoute
  TrustReviewDealIdRoute: typeof TrustReviewDealIdRoute
}

const TrustRouteChildren: TrustRouteChildren = {
  TrustDisputesRoute: TrustDisputesRouteWithChildren,
  TrustKycRoute: TrustKycRoute,
  TrustReviewsRoute: TrustReviewsRoute,
  TrustReviewDealIdRoute: TrustReviewDealIdRoute,
}

const TrustRouteWithChildren = TrustRoute._addFileChildren(TrustRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CorporateRoute: CorporateRouteWithChildren,
  FeedRoute: FeedRoute,
  HostRoute: HostRouteWithChildren,
  OffersRoute: OffersRouteWithChildren,
  RoleRoute: RoleRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRouteWithChildren,
  PaymentsMethodsRoute: PaymentsMethodsRoute,
  PaymentsPayoutsRoute: PaymentsPayoutsRoute,
  SignupCorporateRoute: SignupCorporateRoute,
  SignupHostRoute: SignupHostRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  PaymentsReceiptsTxnIdRoute: PaymentsReceiptsTxnIdRoute,
  PaymentsReceiptsIndexRoute: PaymentsReceiptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
