/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TripRouteImport } from './routes/trip'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RoleRouteImport } from './routes/role'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as RideRequestsRouteImport } from './routes/ride-requests'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrgRouteImport } from './routes/org'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindRouteImport } from './routes/find'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/org.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TripRideIdRouteImport } from './routes/trip_.$rideId'
import { Route as RidesRideIdRouteImport } from './routes/rides_.$rideId'
import { Route as RideRequestsRideIdRouteImport } from './routes/ride-requests_.$rideId'
import { Route as ProfileDriverApplicationRouteImport } from './routes/profile_.driver-application'
import { Route as OrgStaffRouteImport } from './routes/org.staff'
import { Route as OrgSettingsRouteImport } from './routes/org.settings'
import { Route as OrgRidesRouteImport } from './routes/org.rides'
import { Route as OrgPoliciesRouteImport } from './routes/org.policies'
import { Route as OrgPickupHubsRouteImport } from './routes/org.pickup-hubs'
import { Route as OrgMembersRouteImport } from './routes/org.members'
import { Route as OrgEventsRouteImport } from './routes/org.events'
import { Route as OrgDriverApplicationsRouteImport } from './routes/org.driver-applications'
import { Route as OrgDomainRouteImport } from './routes/org.domain'
import { Route as OrgCampusesRouteImport } from './routes/org.campuses'
import { Route as OrgBrandingRouteImport } from './routes/org.branding'
import { Route as OnboardingOrganizationRouteImport } from './routes/onboarding.organization'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSafetyRouteImport } from './routes/admin.safety'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminMoreRouteImport } from './routes/admin.more'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminFinanceIndexRouteImport } from './routes/admin.finance.index'
import { Route as OrgEventsNewRouteImport } from './routes/org.events_.new'
import { Route as OrgEventsEventIdRouteImport } from './routes/org.events_.$eventId'
import { Route as EventEventIdPickupsRouteImport } from './routes/event.$eventId_.pickups'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminFinanceTransactionsRouteImport } from './routes/admin.finance.transactions'
import { Route as AdminFinancePayoutsRouteImport } from './routes/admin.finance.payouts'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRequestsRoute = RideRequestsRouteImport.update({
  id: '/ride-requests',
  path: '/ride-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TripRideIdRoute = TripRideIdRouteImport.update({
  id: '/trip_/$rideId',
  path: '/trip/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRideIdRoute = RidesRideIdRouteImport.update({
  id: '/rides_/$rideId',
  path: '/rides/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRequestsRideIdRoute = RideRequestsRideIdRouteImport.update({
  id: '/ride-requests_/$rideId',
  path: '/ride-requests/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDriverApplicationRoute =
  ProfileDriverApplicationRouteImport.update({
    id: '/profile_/driver-application',
    path: '/profile/driver-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgStaffRoute = OrgStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgRoute,
} as any)
const OrgRidesRoute = OrgRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => OrgRoute,
} as any)
const OrgPoliciesRoute = OrgPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => OrgRoute,
} as any)
const OrgPickupHubsRoute = OrgPickupHubsRouteImport.update({
  id: '/pickup-hubs',
  path: '/pickup-hubs',
  getParentRoute: () => OrgRoute,
} as any)
const OrgMembersRoute = OrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgRoute,
} as any)
const OrgEventsRoute = OrgEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => OrgRoute,
} as any)
const OrgDriverApplicationsRoute = OrgDriverApplicationsRouteImport.update({
  id: '/driver-applications',
  path: '/driver-applications',
  getParentRoute: () => OrgRoute,
} as any)
const OrgDomainRoute = OrgDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => OrgRoute,
} as any)
const OrgCampusesRoute = OrgCampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => OrgRoute,
} as any)
const OrgBrandingRoute = OrgBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => OrgRoute,
} as any)
const OnboardingOrganizationRoute = OnboardingOrganizationRouteImport.update({
  id: '/onboarding/organization',
  path: '/onboarding/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyRoute = AdminSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoreRoute = AdminMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceIndexRoute = AdminFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AdminRoute,
} as any)
const OrgEventsNewRoute = OrgEventsNewRouteImport.update({
  id: '/events_/new',
  path: '/events/new',
  getParentRoute: () => OrgRoute,
} as any)
const OrgEventsEventIdRoute = OrgEventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => OrgRoute,
} as any)
const EventEventIdPickupsRoute = EventEventIdPickupsRouteImport.update({
  id: '/event/$eventId_/pickups',
  path: '/event/$eventId/pickups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceTransactionsRoute =
  AdminFinanceTransactionsRouteImport.update({
    id: '/finance/transactions',
    path: '/finance/transactions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminFinancePayoutsRoute = AdminFinancePayoutsRouteImport.update({
  id: '/finance/payouts',
  path: '/finance/payouts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/find': typeof FindRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/org': typeof OrgRouteWithChildren
  '/profile': typeof ProfileRoute
  '/ride-requests': typeof RideRequestsRoute
  '/rides': typeof RidesRoute
  '/role': typeof RoleRoute
  '/terms': typeof TermsRoute
  '/trip': typeof TripRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/org/branding': typeof OrgBrandingRoute
  '/org/campuses': typeof OrgCampusesRoute
  '/org/domain': typeof OrgDomainRoute
  '/org/driver-applications': typeof OrgDriverApplicationsRoute
  '/org/events': typeof OrgEventsRoute
  '/org/members': typeof OrgMembersRoute
  '/org/pickup-hubs': typeof OrgPickupHubsRoute
  '/org/policies': typeof OrgPoliciesRoute
  '/org/rides': typeof OrgRidesRoute
  '/org/settings': typeof OrgSettingsRoute
  '/org/staff': typeof OrgStaffRoute
  '/profile/driver-application': typeof ProfileDriverApplicationRoute
  '/ride-requests/$rideId': typeof RideRequestsRideIdRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/trip/$rideId': typeof TripRideIdRoute
  '/admin/': typeof AdminIndexRoute
  '/org/': typeof OrgIndexRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/event/$eventId/pickups': typeof EventEventIdPickupsRoute
  '/org/events/$eventId': typeof OrgEventsEventIdRoute
  '/org/events/new': typeof OrgEventsNewRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/find': typeof FindRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/profile': typeof ProfileRoute
  '/ride-requests': typeof RideRequestsRoute
  '/rides': typeof RidesRoute
  '/role': typeof RoleRoute
  '/terms': typeof TermsRoute
  '/trip': typeof TripRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/org/branding': typeof OrgBrandingRoute
  '/org/campuses': typeof OrgCampusesRoute
  '/org/domain': typeof OrgDomainRoute
  '/org/driver-applications': typeof OrgDriverApplicationsRoute
  '/org/events': typeof OrgEventsRoute
  '/org/members': typeof OrgMembersRoute
  '/org/pickup-hubs': typeof OrgPickupHubsRoute
  '/org/policies': typeof OrgPoliciesRoute
  '/org/rides': typeof OrgRidesRoute
  '/org/settings': typeof OrgSettingsRoute
  '/org/staff': typeof OrgStaffRoute
  '/profile/driver-application': typeof ProfileDriverApplicationRoute
  '/ride-requests/$rideId': typeof RideRequestsRideIdRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/trip/$rideId': typeof TripRideIdRoute
  '/admin': typeof AdminIndexRoute
  '/org': typeof OrgIndexRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/event/$eventId/pickups': typeof EventEventIdPickupsRoute
  '/org/events/$eventId': typeof OrgEventsEventIdRoute
  '/org/events/new': typeof OrgEventsNewRoute
  '/admin/finance': typeof AdminFinanceIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/find': typeof FindRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/org': typeof OrgRouteWithChildren
  '/profile': typeof ProfileRoute
  '/ride-requests': typeof RideRequestsRoute
  '/rides': typeof RidesRoute
  '/role': typeof RoleRoute
  '/terms': typeof TermsRoute
  '/trip': typeof TripRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/org/branding': typeof OrgBrandingRoute
  '/org/campuses': typeof OrgCampusesRoute
  '/org/domain': typeof OrgDomainRoute
  '/org/driver-applications': typeof OrgDriverApplicationsRoute
  '/org/events': typeof OrgEventsRoute
  '/org/members': typeof OrgMembersRoute
  '/org/pickup-hubs': typeof OrgPickupHubsRoute
  '/org/policies': typeof OrgPoliciesRoute
  '/org/rides': typeof OrgRidesRoute
  '/org/settings': typeof OrgSettingsRoute
  '/org/staff': typeof OrgStaffRoute
  '/profile_/driver-application': typeof ProfileDriverApplicationRoute
  '/ride-requests_/$rideId': typeof RideRequestsRideIdRoute
  '/rides_/$rideId': typeof RidesRideIdRoute
  '/trip_/$rideId': typeof TripRideIdRoute
  '/admin/': typeof AdminIndexRoute
  '/org/': typeof OrgIndexRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/transactions': typeof AdminFinanceTransactionsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/event/$eventId_/pickups': typeof EventEventIdPickupsRoute
  '/org/events_/$eventId': typeof OrgEventsEventIdRoute
  '/org/events_/new': typeof OrgEventsNewRoute
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community'
    | '/events'
    | '/find'
    | '/login'
    | '/offer'
    | '/org'
    | '/profile'
    | '/ride-requests'
    | '/rides'
    | '/role'
    | '/terms'
    | '/trip'
    | '/waitlist'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/disputes'
    | '/admin/kyc'
    | '/admin/moderation'
    | '/admin/more'
    | '/admin/organizations'
    | '/admin/safety'
    | '/admin/settings'
    | '/event/$eventId'
    | '/onboarding/organization'
    | '/org/branding'
    | '/org/campuses'
    | '/org/domain'
    | '/org/driver-applications'
    | '/org/events'
    | '/org/members'
    | '/org/pickup-hubs'
    | '/org/policies'
    | '/org/rides'
    | '/org/settings'
    | '/org/staff'
    | '/profile/driver-application'
    | '/ride-requests/$rideId'
    | '/rides/$rideId'
    | '/trip/$rideId'
    | '/admin/'
    | '/org/'
    | '/admin/finance/payouts'
    | '/admin/finance/transactions'
    | '/admin/users/$userId'
    | '/event/$eventId/pickups'
    | '/org/events/$eventId'
    | '/org/events/new'
    | '/admin/finance/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/events'
    | '/find'
    | '/login'
    | '/offer'
    | '/profile'
    | '/ride-requests'
    | '/rides'
    | '/role'
    | '/terms'
    | '/trip'
    | '/waitlist'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/disputes'
    | '/admin/kyc'
    | '/admin/moderation'
    | '/admin/more'
    | '/admin/organizations'
    | '/admin/safety'
    | '/admin/settings'
    | '/event/$eventId'
    | '/onboarding/organization'
    | '/org/branding'
    | '/org/campuses'
    | '/org/domain'
    | '/org/driver-applications'
    | '/org/events'
    | '/org/members'
    | '/org/pickup-hubs'
    | '/org/policies'
    | '/org/rides'
    | '/org/settings'
    | '/org/staff'
    | '/profile/driver-application'
    | '/ride-requests/$rideId'
    | '/rides/$rideId'
    | '/trip/$rideId'
    | '/admin'
    | '/org'
    | '/admin/finance/payouts'
    | '/admin/finance/transactions'
    | '/admin/users/$userId'
    | '/event/$eventId/pickups'
    | '/org/events/$eventId'
    | '/org/events/new'
    | '/admin/finance'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/community'
    | '/events'
    | '/find'
    | '/login'
    | '/offer'
    | '/org'
    | '/profile'
    | '/ride-requests'
    | '/rides'
    | '/role'
    | '/terms'
    | '/trip'
    | '/waitlist'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/disputes'
    | '/admin/kyc'
    | '/admin/moderation'
    | '/admin/more'
    | '/admin/organizations'
    | '/admin/safety'
    | '/admin/settings'
    | '/event/$eventId'
    | '/onboarding/organization'
    | '/org/branding'
    | '/org/campuses'
    | '/org/domain'
    | '/org/driver-applications'
    | '/org/events'
    | '/org/members'
    | '/org/pickup-hubs'
    | '/org/policies'
    | '/org/rides'
    | '/org/settings'
    | '/org/staff'
    | '/profile_/driver-application'
    | '/ride-requests_/$rideId'
    | '/rides_/$rideId'
    | '/trip_/$rideId'
    | '/admin/'
    | '/org/'
    | '/admin/finance/payouts'
    | '/admin/finance/transactions'
    | '/admin/users/$userId'
    | '/event/$eventId_/pickups'
    | '/org/events_/$eventId'
    | '/org/events_/new'
    | '/admin/finance/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  FindRoute: typeof FindRoute
  LoginRoute: typeof LoginRoute
  OfferRoute: typeof OfferRoute
  OrgRoute: typeof OrgRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RideRequestsRoute: typeof RideRequestsRoute
  RidesRoute: typeof RidesRoute
  RoleRoute: typeof RoleRoute
  TermsRoute: typeof TermsRoute
  TripRoute: typeof TripRoute
  WaitlistRoute: typeof WaitlistRoute
  EventEventIdRoute: typeof EventEventIdRoute
  OnboardingOrganizationRoute: typeof OnboardingOrganizationRoute
  ProfileDriverApplicationRoute: typeof ProfileDriverApplicationRoute
  RideRequestsRideIdRoute: typeof RideRequestsRideIdRoute
  RidesRideIdRoute: typeof RidesRideIdRoute
  TripRideIdRoute: typeof TripRideIdRoute
  EventEventIdPickupsRoute: typeof EventEventIdPickupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride-requests': {
      id: '/ride-requests'
      path: '/ride-requests'
      fullPath: '/ride-requests'
      preLoaderRoute: typeof RideRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trip_/$rideId': {
      id: '/trip_/$rideId'
      path: '/trip/$rideId'
      fullPath: '/trip/$rideId'
      preLoaderRoute: typeof TripRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides_/$rideId': {
      id: '/rides_/$rideId'
      path: '/rides/$rideId'
      fullPath: '/rides/$rideId'
      preLoaderRoute: typeof RidesRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride-requests_/$rideId': {
      id: '/ride-requests_/$rideId'
      path: '/ride-requests/$rideId'
      fullPath: '/ride-requests/$rideId'
      preLoaderRoute: typeof RideRequestsRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/driver-application': {
      id: '/profile_/driver-application'
      path: '/profile/driver-application'
      fullPath: '/profile/driver-application'
      preLoaderRoute: typeof ProfileDriverApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/staff': {
      id: '/org/staff'
      path: '/staff'
      fullPath: '/org/staff'
      preLoaderRoute: typeof OrgStaffRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/settings': {
      id: '/org/settings'
      path: '/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/rides': {
      id: '/org/rides'
      path: '/rides'
      fullPath: '/org/rides'
      preLoaderRoute: typeof OrgRidesRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/policies': {
      id: '/org/policies'
      path: '/policies'
      fullPath: '/org/policies'
      preLoaderRoute: typeof OrgPoliciesRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/pickup-hubs': {
      id: '/org/pickup-hubs'
      path: '/pickup-hubs'
      fullPath: '/org/pickup-hubs'
      preLoaderRoute: typeof OrgPickupHubsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/members': {
      id: '/org/members'
      path: '/members'
      fullPath: '/org/members'
      preLoaderRoute: typeof OrgMembersRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/events': {
      id: '/org/events'
      path: '/events'
      fullPath: '/org/events'
      preLoaderRoute: typeof OrgEventsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/driver-applications': {
      id: '/org/driver-applications'
      path: '/driver-applications'
      fullPath: '/org/driver-applications'
      preLoaderRoute: typeof OrgDriverApplicationsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/domain': {
      id: '/org/domain'
      path: '/domain'
      fullPath: '/org/domain'
      preLoaderRoute: typeof OrgDomainRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/campuses': {
      id: '/org/campuses'
      path: '/campuses'
      fullPath: '/org/campuses'
      preLoaderRoute: typeof OrgCampusesRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/branding': {
      id: '/org/branding'
      path: '/branding'
      fullPath: '/org/branding'
      preLoaderRoute: typeof OrgBrandingRouteImport
      parentRoute: typeof OrgRoute
    }
    '/onboarding/organization': {
      id: '/onboarding/organization'
      path: '/onboarding/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof OnboardingOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety': {
      id: '/admin/safety'
      path: '/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AdminSafetyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/more': {
      id: '/admin/more'
      path: '/more'
      fullPath: '/admin/more'
      preLoaderRoute: typeof AdminMoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/': {
      id: '/admin/finance/'
      path: '/finance'
      fullPath: '/admin/finance/'
      preLoaderRoute: typeof AdminFinanceIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/org/events_/new': {
      id: '/org/events_/new'
      path: '/events/new'
      fullPath: '/org/events/new'
      preLoaderRoute: typeof OrgEventsNewRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/events_/$eventId': {
      id: '/org/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/org/events/$eventId'
      preLoaderRoute: typeof OrgEventsEventIdRouteImport
      parentRoute: typeof OrgRoute
    }
    '/event/$eventId_/pickups': {
      id: '/event/$eventId_/pickups'
      path: '/event/$eventId/pickups'
      fullPath: '/event/$eventId/pickups'
      preLoaderRoute: typeof EventEventIdPickupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/transactions': {
      id: '/admin/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/admin/finance/transactions'
      preLoaderRoute: typeof AdminFinanceTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/payouts': {
      id: '/admin/finance/payouts'
      path: '/finance/payouts'
      fullPath: '/admin/finance/payouts'
      preLoaderRoute: typeof AdminFinancePayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminMoreRoute: typeof AdminMoreRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminSafetyRoute: typeof AdminSafetyRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFinancePayoutsRoute: typeof AdminFinancePayoutsRoute
  AdminFinanceTransactionsRoute: typeof AdminFinanceTransactionsRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminFinanceIndexRoute: typeof AdminFinanceIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminKycRoute: AdminKycRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminMoreRoute: AdminMoreRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminSafetyRoute: AdminSafetyRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFinancePayoutsRoute: AdminFinancePayoutsRoute,
  AdminFinanceTransactionsRoute: AdminFinanceTransactionsRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminFinanceIndexRoute: AdminFinanceIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrgRouteChildren {
  OrgBrandingRoute: typeof OrgBrandingRoute
  OrgCampusesRoute: typeof OrgCampusesRoute
  OrgDomainRoute: typeof OrgDomainRoute
  OrgDriverApplicationsRoute: typeof OrgDriverApplicationsRoute
  OrgEventsRoute: typeof OrgEventsRoute
  OrgMembersRoute: typeof OrgMembersRoute
  OrgPickupHubsRoute: typeof OrgPickupHubsRoute
  OrgPoliciesRoute: typeof OrgPoliciesRoute
  OrgRidesRoute: typeof OrgRidesRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  OrgStaffRoute: typeof OrgStaffRoute
  OrgIndexRoute: typeof OrgIndexRoute
  OrgEventsEventIdRoute: typeof OrgEventsEventIdRoute
  OrgEventsNewRoute: typeof OrgEventsNewRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgBrandingRoute: OrgBrandingRoute,
  OrgCampusesRoute: OrgCampusesRoute,
  OrgDomainRoute: OrgDomainRoute,
  OrgDriverApplicationsRoute: OrgDriverApplicationsRoute,
  OrgEventsRoute: OrgEventsRoute,
  OrgMembersRoute: OrgMembersRoute,
  OrgPickupHubsRoute: OrgPickupHubsRoute,
  OrgPoliciesRoute: OrgPoliciesRoute,
  OrgRidesRoute: OrgRidesRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  OrgStaffRoute: OrgStaffRoute,
  OrgIndexRoute: OrgIndexRoute,
  OrgEventsEventIdRoute: OrgEventsEventIdRoute,
  OrgEventsNewRoute: OrgEventsNewRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  FindRoute: FindRoute,
  LoginRoute: LoginRoute,
  OfferRoute: OfferRoute,
  OrgRoute: OrgRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RideRequestsRoute: RideRequestsRoute,
  RidesRoute: RidesRoute,
  RoleRoute: RoleRoute,
  TermsRoute: TermsRoute,
  TripRoute: TripRoute,
  WaitlistRoute: WaitlistRoute,
  EventEventIdRoute: EventEventIdRoute,
  OnboardingOrganizationRoute: OnboardingOrganizationRoute,
  ProfileDriverApplicationRoute: ProfileDriverApplicationRoute,
  RideRequestsRideIdRoute: RideRequestsRideIdRoute,
  RidesRideIdRoute: RidesRideIdRoute,
  TripRideIdRoute: TripRideIdRoute,
  EventEventIdPickupsRoute: EventEventIdPickupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
