-- DESIGN BLUEPRINT ONLY. Do not apply to production without review.
create extension if not exists pgcrypto;
create type public.org_role as enum ('member','organization_staff','organization_admin');
create type public.event_status as enum ('draft','published','carpool_open','live','completed','archived');
create type public.ride_status as enum ('draft','open','full','boarding','active','completed','cancelled');
create type public.request_status as enum ('pending','accepted','declined','cancelled','expired','waitlisted');

create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,status text not null default 'trial',created_at timestamptz not null default now());
create table public.organization_branding(organization_id uuid primary key references public.organizations on delete cascade,portal_name text not null,primary_color text,accent_color text,logo_url text,favicon_url text,welcome_message text,support_email text,support_phone text);
create table public.organization_domains(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,hostname text not null unique,is_primary boolean not null default false,status text not null default 'pending');
create table public.campuses(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,name text not null,city text,active boolean not null default true);
create table public.organization_memberships(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,user_id uuid not null references auth.users on delete cascade,role public.org_role not null default 'member',status text not null default 'active',unique(organization_id,user_id));
create table public.organization_policies(organization_id uuid primary key references public.organizations on delete cascade,require_member_verification boolean not null default true,require_driver_verification boolean not null default true,require_vehicle_verification boolean not null default true,allow_contributions boolean not null default false,max_contribution numeric,enable_waitlist boolean not null default true);
create table public.pickup_hubs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,campus_id uuid references public.campuses on delete set null,name text not null,area text not null,latitude double precision,longitude double precision,active boolean not null default true);
create table public.events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,campus_id uuid references public.campuses on delete set null,name text not null,description text,venue text,starts_at timestamptz,ends_at timestamptz,carpool_opens_at timestamptz,carpool_closes_at timestamptz,status public.event_status not null default 'draft');
create table public.vehicles(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,user_id uuid not null references auth.users on delete cascade,make text,model text,color text,plate_number text,verification_status text not null default 'pending');
create table public.rides(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,event_id uuid not null references public.events on delete cascade,driver_id uuid not null references auth.users,direction text not null check(direction in ('outbound','return')),vehicle_id uuid references public.vehicles,origin_area text not null,pickup_hub_id uuid references public.pickup_hubs,departure_at timestamptz not null,seats_total int not null check(seats_total>0),seats_available int not null check(seats_available>=0),contribution numeric not null default 0,status public.ride_status not null default 'open');
create table public.seat_requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,event_id uuid not null references public.events on delete cascade,ride_id uuid not null references public.rides on delete cascade,passenger_id uuid not null references auth.users,status public.request_status not null default 'pending',created_at timestamptz not null default now(),unique(ride_id,passenger_id));
create table public.ride_participants(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,event_id uuid not null references public.events on delete cascade,ride_id uuid not null references public.rides on delete cascade,user_id uuid not null references auth.users,mode text not null check(mode in ('driver','passenger')),status text not null,unique(ride_id,user_id));
create table public.waitlist_entries(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,event_id uuid not null references public.events on delete cascade,user_id uuid not null references auth.users,direction text not null,origin_area text not null,window_start timestamptz,window_end timestamptz,seats int not null default 1,status text not null default 'active');
create table public.incidents(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete cascade,event_id uuid references public.events on delete set null,ride_id uuid references public.rides on delete set null,reporter_id uuid not null references auth.users,subject_user_id uuid references auth.users,status text not null default 'open',summary text not null,created_at timestamptz not null default now());
create table public.audit_logs(id bigint generated always as identity primary key,organization_id uuid references public.organizations on delete set null,actor_id uuid references auth.users,action text not null,entity_type text not null,entity_id text,metadata jsonb not null default '{}',created_at timestamptz not null default now());

create or replace function public.is_org_member(org uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.organization_memberships m where m.organization_id=org and m.user_id=auth.uid() and m.status='active')$$;
create or replace function public.is_org_admin(org uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.organization_memberships m where m.organization_id=org and m.user_id=auth.uid() and m.status='active' and m.role in ('organization_admin','organization_staff'))$$;

alter table public.campuses enable row level security; alter table public.organization_memberships enable row level security; alter table public.organization_policies enable row level security; alter table public.pickup_hubs enable row level security; alter table public.events enable row level security; alter table public.vehicles enable row level security; alter table public.rides enable row level security; alter table public.seat_requests enable row level security; alter table public.ride_participants enable row level security; alter table public.waitlist_entries enable row level security; alter table public.incidents enable row level security;
create policy "members read tenant events" on public.events for select using(public.is_org_member(organization_id));
create policy "members read tenant rides" on public.rides for select using(public.is_org_member(organization_id));
create policy "admins manage events" on public.events for all using(public.is_org_admin(organization_id)) with check(public.is_org_admin(organization_id));
create policy "admins manage hubs" on public.pickup_hubs for all using(public.is_org_admin(organization_id)) with check(public.is_org_admin(organization_id));
create policy "members read own tenant hubs" on public.pickup_hubs for select using(public.is_org_member(organization_id));
create policy "users manage own seat requests" on public.seat_requests for select using(passenger_id=auth.uid() or public.is_org_admin(organization_id));
-- Seat acceptance MUST be implemented through a transaction/RPC that locks the ride row,
-- validates tenant/event/request consistency and decrements seats_available atomically.
